services:
  beszel:
    image: henrygd/beszel:latest
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
volumes:
  beszel_data:
    external: true