version: '3.8'

services:
  owlbank:
    image: dumbwareio/dumbbudget:latest
    container_name: owlbank
    restart: unless-stopped
    ports:
      - "3862:3000"
    volumes:
      - "${DUMBBUDGET_DATA_PATH}:/app/data"
    environment:
      - DUMBBUDGET_PIN=${DUMBBUDGET_PIN}
      - BASE_URL=${DUMBBUDGET_BASE_URL}
      - CURRENCY=${DUMBBUDGET_CURRENCY}
      - SITE_TITLE=${DUMBBUDGET_SITE_TITLE}
      - INSTANCE_NAME=${DUMBBUDGET_INSTANCE_NAME}
      # Optional: Restrict origins
      # - ALLOWED_ORIGINS=${DUMBBUDGET_ALLOWED_ORIGINS:-http://localhost:3000}
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000"]
    #   start_period: 20s
    #   interval: 20s
    #   timeout: 5s
    #   retries: 3