services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - calibre-books:/books
      - calibre-data:/config
    ports:
      - 8083:8083
volumes:
  calibre-books:
    external: true
  calibre-data: 
    external: true