version: '3.8'

services:
  foundryvtt:
    image: felddy/foundryvtt:13
    hostname: my_foundry_host
    volumes:
      - foundry-data:/data
    environment:
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY}
    ports:
      - "30000:30000"

volumes:
  foundry-data:
    external: true